version: "3"
services:


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /usr/backend
    

    volumes:
            - ./backend:/usr/backend
    expose:
      - 8000
    ports:
      - "8000:8000"
  esummit22-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /usr/frontend

    expose:
      - 3000
    ports:
      - "3000:3000" 


  
volumes:
  # static-ui-content:
  static-ui-content: