# Generated by Django 5.0 on 2024-01-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_organization_owner_user_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drone_images/'),
        ),
    ]
