# Generated by Django 5.0.2 on 2024-02-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_drone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='secret',
            field=models.CharField(default='abcd', max_length=16),
            preserve_default=False,
        ),
    ]
